thread safe bug fixed.
koledeus/koledeus-client pull request #4
Opened 2021-01-11 19:43 UTC by recepdmr

2021-01-11 21:06 UTC, peacecwz commented
@recepdmr You have conlicts, can you fix conflicts?

2021-01-11 21:08 UTC, peacecwz requested changes
@recepdmr You have conlicts, can you fix conflicts?

2021-01-13 16:22 UTC, recepdmr commented
@peacecwz ok. I will fix.

2021-01-13 20:27 UTC, peacecwz requested changes

2021-01-13 20:27 UTC, peacecwz commented on src/Koledeus.Client/Services/ICPUInfoService.cs
> +            foreach (var process in processes)
It doesn't solve it in a better way. You need to use Parallel working and handling race condition with Parallel.Foreach :)

2021-01-14 19:23 UTC, closed without merging